import json
from pathlib import Path
from google import genai
from google.genai import types


# ============================================================
# CONFIGURATION
# ============================================================

DATA_JSON = Path(
    "/home/student01/Downloads/data.json"
)

OUTPUT_JSON = Path(
    "/home/student01/Downloads/gemini_video_descriptions.json"
)

# Use the Gemini model you want to test.
# Replace this if you want to use another currently available model.
GEMINI_MODEL = "gemini-3.6-flash"

# Your Q3 = independent frame description
DESCRIPTION_INDEX = 5


# ============================================================
# GEMINI CLIENT
# ============================================================

client = genai.Client()


# ============================================================
# PROMPT
# ============================================================
'''
VIDEO_DESCRIPTION_PROMPT = """
You are analyzing a cooking video using a sequence of descriptions
generated independently for sampled frames of the video.

Your task is to reconstruct the cooking process as accurately and
comprehensively as possible from these frame descriptions.

IMPORTANT:

1. The frame descriptions are observations of individual frames.
2. Preserve the temporal order of the frames.
3. Do NOT treat each frame as an independent event.
4. Connect consecutive frames when they clearly represent the same
   ongoing activity.
5. Identify meaningful changes in the cooking process and even the tiniest changes in the state of the food.
6. Track ingredients as they are introduced, combined, transferred,
   cooked, mixed, heated, or otherwise manipulated.
7. Track utensils and containers when the descriptions provide enough
   evidence to do so.
8. Distinguish between actions that continue across multiple frames
   and genuinely new actions.
9. Do not invent events that are not supported by the frame
   descriptions.
10. If something is uncertain, explicitly indicate that it is uncertain.
11. Preserve as much useful detail as possible.
12. Do not give a short summary. The goal is a highly detailed
    reconstruction of the entire cooking process.

The input below contains descriptions in chronological order.

For every frame, the frame number and timestamp are provided.

Produce a highly detailed temporal description of the entire video.

Your response should:

- Begin with a brief overview of what the video appears to depict.
- Then describe the video chronologically.
- Explain what happens at each meaningful stage.
- Mention transitions between stages.
- Mention ingredients when they appear or change state.
- Mention mixing, stirring, chopping, pouring, heating, baking,
  transferring, etc. when supported by the evidence.
- Preserve important visual details from the frame descriptions.
- Track every smallest change in the state of the food
- Do not collapse the entire video into a generic recipe.
- Do not invent ingredients, quantities, actions, or steps.

The goal is to reconstruct the most detailed and coherent description
of what happens throughout the video from beginning to end.
"""
'''

VIDEO_DESCRIPTION_PROMPT = """
You are analyzing a cooking video using a chronological sequence of
context-aware descriptions generated for individual video frames.

Each description was generated by a vision-language model that was
given limited context from preceding frames. Therefore, the
descriptions may contain information carried forward from earlier
frames as well as information about the current frame.

Your task is to reconstruct the cooking process as accurately and
comprehensively as possible from these descriptions.

Preserve the chronological order of the frames.

Use the descriptions to identify:
- what is happening at each stage,
- how the cooking process changes over time,
- how ingredients are introduced, combined, transferred, or transformed,
- how utensils and containers are used,
- how one action leads to another,
- and important transitions between stages.

Do not simply concatenate or repeat the frame descriptions.

Instead, synthesize them into one coherent, highly detailed account
of the entire cooking video.

However, do not invent actions, ingredients, quantities, or events that
are not supported by the provided descriptions. If something is
uncertain, make that uncertainty clear.

Preserve important temporal information and do not reduce the video to
a generic recipe.

Provide a highly detailed chronological reconstruction from beginning
to end.
"""


# ============================================================
# EXTRACT FRAME DESCRIPTIONS
# ============================================================

def extract_frame_descriptions(video):
    """
    Extract context-aware descriptions for every frame.

    The descriptions are stored in:
        frame["context_description"]

    The timestamp is calculated from:
        frame_number / video FPS
    """

    descriptions = []

    fps = video["fps"]

    for frame in video["frames"]:

        if "context_description" not in frame:
            raise ValueError(
                f"Frame {frame['frame_number']} does not contain "
                "'context_description'"
            )

        frame_number = frame["frame_number"]

        descriptions.append({
            "frame_number": frame_number,
            "timestamp": frame_number / fps,
            "description": frame["context_description"]
        })

    return descriptions

# ============================================================
# BUILD GEMINI INPUT
# ============================================================

def build_gemini_input(frame_descriptions):

    sections = []

    for item in frame_descriptions:

        section = (
            f"\n--- FRAME {item['frame_number']} "
            f"({item['timestamp']:.2f} seconds) ---\n"
            f"{item['description']}\n"
        )

        sections.append(section)

    return "".join(sections)


# ============================================================
# GENERATE VIDEO DESCRIPTION
# ============================================================

def generate_video_description(video):

    video_name = video["video_name"]

    print("\n" + "=" * 80)
    print(f"PROCESSING VIDEO: {video_name}")
    print("=" * 80)

    frame_descriptions = extract_frame_descriptions(video)

    print(
        f"Found {len(frame_descriptions)} frame descriptions."
    )

    frame_text = build_gemini_input(frame_descriptions)

    full_prompt = (
        VIDEO_DESCRIPTION_PROMPT
        + "\n\n"
        + "FRAME-BY-FRAME OBSERVATIONS:\n"
        + frame_text
    )

    print("\nSending frame descriptions to Gemini...")

    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=full_prompt,
        config=types.GenerateContentConfig(
            max_output_tokens=10000
        )
    )

    description = response.text.strip()

    print("\n" + "=" * 80)
    print("GEMINI VIDEO DESCRIPTION")
    print("=" * 80)
    print(description)

    return {
        "video_name": video_name,
        "num_frames": len(frame_descriptions),
        "frame_descriptions": frame_descriptions,
        "video_description": description
    }


# ============================================================
# MAIN
# ============================================================

def main():

    if not DATA_JSON.exists():
        raise FileNotFoundError(
            f"Could not find {DATA_JSON}"
        )

    print(f"Loading Qwen results from:\n{DATA_JSON}")

    with open(DATA_JSON, "r") as f:
        videos = json.load(f)

    results = []

    for video in videos:

        result = generate_video_description(video)

        results.append(result)

    # Save everything
    with open(OUTPUT_JSON, "w") as f:
        json.dump(
            results,
            f,
            indent=4,
            ensure_ascii=False
        )

    print("\n" + "=" * 80)
    print("DONE")
    print("=" * 80)

    print(
        f"Saved Gemini results to:\n{OUTPUT_JSON}"
    )


if __name__ == "__main__":
    main()
